# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_c_compilerclang
    - CONFIG=osx_c_compilertoolchain_c

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "lyViFD5Qj5Yp+FzdmUusJrm5I/GSdvp7kuYQLs/kScrHC3xH/u7TnuYqxSCm0tHr66Jyj9PdxAeODxQ7HNE+qJn3FuaFCvIEIk4F7/9cY0a3OCnSzvmiEi2BmioGZqqiIaNPyAvBzw4DutmQJaGYnWAIf5JHs0xCZZgMVh/XKVpkpYf1pn5AVXbqElL17nEKnXC7MTjUFcfam52F0MQRo1WYEWC+aSQdL6oKvW3IhMmCKIHs1Tj6o3JVHTtmIwi52hXtZ7GNb6UW67BDZw4zy5w34rTTLCdl3zbEXsOtt4kDC1qeVd0mJEOgg/1yGXq1W8w+D4M46l32bWbfJ1TerSomMrd/UgcQ2NX2RoHeqlTm0QrRUR2wqOIW37glH580CqFt3JMVvLTvh7kN8Ff9dWyGDBcUCaV4nw1J3sIGzCJKwXUzWisIpsdZbolznV0k/T9CQG5sNUxa17SJk8KYEaVrSs7ryWMFkIZmzFJ3MLTn0hXND5ymEf9LLtg1emZGgr6btWqxr2RM9ce5v9YthjkaY9N8K1Ym8LqdUWGmQ9U4n0BsC+MZ2xhVRR30DmyTI/VqLGo3Roch0qA+KRr2F82YRSXaVVelk4wsNCk5YrPvxijIfJt3Rd2c9FeHA5iDx31/HzX3sVVzcVf7WC6x2YxfQehmbZLWIVeXl+Wda6Y="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml